[
build
]
  command = "ng build --prod"
  publish = "dist/DyweWelcomePage"

[
functions
]
  directory = "functions"

[
headers
]
  [[
headers
]]
    for = "/*"
    [
headers.values
]
      "X-Frame-Options" = "DENY"
      "X-Content-Type-Options" = "nosniff"

[
redirects
]
  [[
redirects
]]
    from = "/*"
    to = "/index.html"
    status = 200